// ── 색 토큰 — CSS 변수 참조 (index.css의 :root / [data-testmode]에서 정의) ──
// 기본은 잔잔한 쿨톤, 테스트 모드에선 전체가 웜톤으로 전환됨.
export const c = {
  canvas: 'var(--canvas)',
  surface: 'var(--surface)',
  surface2: 'var(--surface-2)',
  ink: 'var(--ink)',
  inkStrong: 'var(--ink-strong)',
  muted: 'var(--muted)',
  faint: 'var(--faint)',
  line: 'var(--line)',
  lineStrong: 'var(--line-strong)',
  accent: 'var(--accent)',
  accentSoft: 'var(--accent-soft)',
  accentLine: 'var(--accent-line)',
  warnBg: 'var(--warn-bg)',
  warnInk: 'var(--warn-ink)',
  warnLine: 'var(--warn-line)',
  errBg: 'var(--err-bg)',
  errInk: 'var(--err-ink)',
  errLine: 'var(--err-line)',
  okBg: 'var(--ok-bg)',
  okInk: 'var(--ok-ink)',
  okLine: 'var(--ok-line)',
}
export const mono = "ui-monospace, 'SF Mono', 'JetBrains Mono', Menlo, monospace"

export const ps = {
  page: { minHeight: '100vh', background: c.canvas },
  center: { minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: c.canvas, padding: 24 },
  header: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 24px', height: 56, background: c.surface, borderBottom: `1px solid ${c.line}` },
  headerTitle: { fontSize: 15, fontWeight: 600, color: c.inkStrong, letterSpacing: '-0.01em' },
  backBtn: { background: 'none', border: 'none', fontSize: 14, color: c.accent, cursor: 'pointer' },
  layout: { display: 'flex', gap: 20, padding: 24, maxWidth: 1080, margin: '0 auto', alignItems: 'flex-start' },
  formCol: { flex: 1, display: 'flex', flexDirection: 'column', gap: 12 },
  previewCol: { width: 360, position: 'sticky', top: 24 },
  card: { background: c.surface, border: `1px solid ${c.line}`, borderRadius: 8, padding: 20 },
  cardTitle: { fontSize: 13, fontWeight: 600, color: c.inkStrong, marginBottom: 12 },
  sublabel: { fontSize: 12, color: c.muted, marginBottom: 6 },
  row: { display: 'flex', gap: 0 },
  input: { width: '100%', padding: '10px 12px', border: `1px solid ${c.line}`, borderRadius: 6, fontSize: 14, outline: 'none', boxSizing: 'border-box', fontFamily: 'inherit', background: c.surface, color: c.ink },
  textarea: { width: '100%', padding: '10px 12px', border: `1px solid ${c.line}`, borderRadius: 6, fontSize: 14, outline: 'none', resize: 'vertical', fontFamily: 'inherit', boxSizing: 'border-box', background: c.surface, color: c.ink },
  optBtn: { padding: '8px 14px', border: `1px solid ${c.line}`, borderRadius: 6, background: c.surface, fontSize: 12, cursor: 'pointer', color: c.muted },
  optSel: { border: `1px solid ${c.accent}`, background: c.accentSoft, color: c.accent, fontWeight: 600 },
  error: { background: c.errBg, border: `1px solid ${c.errLine}`, borderRadius: 6, padding: '10px 14px', fontSize: 13, color: c.errInk },
  btnPrimary: { background: c.accent, color: '#fff', border: 'none', borderRadius: 6, padding: '10px 24px', fontSize: 14, fontWeight: 600, cursor: 'pointer', width: '100%' },
  btnSend: { background: c.accent, color: '#fff', border: 'none', borderRadius: 6, padding: '14px', fontSize: 15, fontWeight: 600, cursor: 'pointer', width: '100%' },
  successCard: { background: c.surface, border: `1px solid ${c.line}`, borderRadius: 12, padding: '48px 40px', textAlign: 'center', boxShadow: '0 8px 40px rgba(0,0,0,0.06)' },
  previewTitle: { fontSize: 12, fontWeight: 600, color: c.muted, marginBottom: 8, paddingLeft: 2 },
  previewCard: { background: c.surface, border: `1px solid ${c.line}`, borderRadius: 8, padding: 18 },
  pRow: { display: 'flex', gap: 8, marginBottom: 8, alignItems: 'flex-start' },
  pKey: { fontSize: 11, fontWeight: 600, color: c.faint, minWidth: 52, paddingTop: 1 },
  pVal: { fontSize: 13, color: c.ink, flex: 1, wordBreak: 'break-all' },
  preBody: { fontSize: 11.5, color: c.muted, lineHeight: 1.75, whiteSpace: 'pre-wrap', fontFamily: 'inherit', margin: 0 },
  testModeBanner: { background: c.warnBg, border: `1px solid ${c.warnLine}`, borderRadius: 6, padding: '5px 8px', marginBottom: 8, fontSize: 11, color: c.warnInk },
}
